# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_demo
  pool: 5
  username: root
  password: root123

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_demo
  pool: 5
  username: root
  password: password

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_demo
  pool: 5
  username: manju
  password: password

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: test_demo
  pool: 5
  username: manju
  password: password













































#default: &default
 # adapter: sqlite3
  #pool: 5
  #timeout: 5000

#development:
 # <<: *default
  #database: db/development.sqlite3


#test:
 # <<: *default
  #database: db/test.sqlite3

#production:
 # <<: *default
  #database: db/production.sqlite3
